web:
  #数据库数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: web_manage
    username: root
    password: 20040905
  #本地主机ip和端口
  local:
    datasource:
      host: 139.196.196.178
      port: 8088
  #redis数据源
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
